#+TITLE: Emacs configuration
#+AUTHOR: Tom Hartman
#+STARTUP: overview
#+PROPERTY: header-args:emacs-lisp :tangle ./init-test.el
 
* General Setup
** Preamble
This section contains the license and commentary for this elisp file. This both makes my elisp linter happy and also makes me happy. Or at least makes me feel like a responsible programmer.

*** License and Information
This configuration uses the GPL v2 license.

#+begin_src emacs-lisp
;;; init.el --- Emacs configuration and initialization file

;; Copyright (c) 2020 Thomas Hartman (thomas.lees.hartman@gmail.com)

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License
;; as published by the Free Software Foundation; either version 2
;; of the License, or the License, or (at your option) any later
;; version.

;; This program is distributed in the hope that it will be useful
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
#+end_src


*** Commentary
#+begin_src emacs-lisp
;;; Commentary:
;; This is my Emacs configuration file.There are many like it but this one is mine.
;;
;; There is a lot of code in here that was lifted or modified from
;; other sources.Below is a non-exhaustive list of them:
;;
;; System Crafters Emacs from Scratch: https://github.com/daviwil/emacs-from-scratch
;;

;; 
#+end_src


*** And the Code Begins... Nowowowowoowowowowow
#+begin_src emacs-lisp
;;; Code:
#+end_src

** Bars
 Remove the menu, scroll, and toolbar. Remove the basic line number
 mode as well.

 #+begin_src emacs-lisp output

 (menu-bar-mode -1)
 (scroll-bar-mode -1)
 (tool-bar-mode -1)

 #+end_src

** Line Numbers
#+begin_src emacs-lisp

;; Set up the visible bell
(setq visible-bell t)

(column-number-mode)
(global-display-line-numbers-mode t)

;; Set frame transparency
;;(set-frame-parameter (selected-frame) 'alpha efs/frame-transparency)
;;(add-to-list 'default-frame-alist `(alpha . ,efs/frame-transparency))
;;(set-frame-parameter (selected-frame) 'fullscreen 'maximized)
;;(add-to-list 'default-frame-alist '(fullscreen . maximized))

;; Disable line numbers for some modes
(dolist (mode '(org-mode-hook
                term-mode-hook
                shell-mode-hook
                treemacs-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

** Frist Buffer

Go directly to scratch buffer, do not pass go
#+begin_src emacs-lisp output

(setq startup-screen-inhibit-startup-screen t)

#+end_src

** Package Setup
Initialize the package repositories. Org mode in mainline emacs can be behind the stable development curve so add that in, in addition to melpa.

Setup the use-package package as well for ease of package management and configuration

   #+begin_src emacs-lisp
     ;; Initialize package sources
     (require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
			 ("elpa" . "https://elpa.gnu.org/packages/")
;;			 ("org" . "https://orgmode.org/elpa/")
			 ))

     (package-initialize)
     (unless package-archive-contents
       (package-refresh-contents))

     ;; Initialize use-package on non-Linux platforms
     (unless (package-installed-p 'use-package)
       (package-install 'use-package))

     (require 'use-package)
     (setq use-package-always-ensure t)

     (use-package auto-package-update
	:ensure t
	:config
	(setq auto-package-update-delete-old-versions t
	      auto-package-update-interval 4)
	(auto-package-update-maybe))
   
   #+end_src

** Constants
#+begin_src emacs-lisp
(defvar *full-name* "Tom Hartman")
(defvar *email* "thomas.lees.hartman@gmail.com")

#+end_src

* Utilities

** Comment lines
#+begin_src emacs-lisp
(defun tlh/comment-lines (str beg end line-width)
  "Return a commented version of STR using BEG, END and LINE-WIDTH."
  (let ((lines (split-string str "\n")))
    (mapconcat #'(lambda (line)
                   (concat beg " " str (make-string (- line-width
                                                       (length str)
                                                       (+ (length beg) 1)
                                                       (length end)) ? )
                           end)) lines "\n")))

#+end_src

* Appearance
This section configures the overall apparance of emacs from fonts to themes, transpancy and other visual nicities.

** Font
Setup SauceCodePro from Nerd Font as the default font for buffers.

#+begin_src emacs-lisp
  
(add-to-list 'default-frame-alist '(font . "SauceCodePro Nerd Font Mono-8"))
 
#+end_src

** Theme
From the doom themes package use the doom-moonlight theme

#+begin_src emacs-lisp

;;(use-package doom-themes
;;  :init (load-theme 'doom-sourcerer t))
(use-package doom-themes
  :init (load-theme 'doom-acario-dark t))

#+end_src

** Transparency
A quick function to set the transparency of emacs when in window mode. I've found 80% to be the most comfortable.

#+begin_src emacs-lisp
(defun set-transparency (value)
  "Set the transparency `VALUE' of the frame window 0=transparent/100=opaque."
  (interactive "nTransparency Value 0 - 100: ")

  (set-frame-parameter (selected-frame) 'alpha value))
   
(set-transparency 90)
#+end_src

** Mixed Pitch
By default org mode is set to use variable pitch mode with tables using fixed pitch but this doesn't quite work as advertise. Mixed pitch mode resolves this issue. Setup is pretty straight forward just add a hook  for org-mode to enable mixed-pitch-mode.

To enable for all text modes add a hook for text-mode.

#+begin_src emacs-lisp
(use-package mixed-pitch
  :hook (org-mode . mixed-pitch-mode))
#+end_src

** All Icon Mode
#+begin_src emacs-lisp
(use-package all-the-icons-dired
  :config
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+end_src

** Mode Line
Updating the mode line for more awesome. Currently playing around with telephone line.

#+begin_src emacs-lisp
(use-package telephone-line
  :custom
  (telephone-line-primary-left-separator 'telephone-line-cubed-left)
  (telephone-line-secondary-left-separator 'telephone-line-cubed-hollow-left)
  (telephone-line-primary-right-separator 'telephone-line-cubed-right)
  (telephone-line-secondary-right-separator 'telephone-line-cubed-hollow-right)
  (telephone-line-height 16)
  (telephone-line-mode 1))
#+end_src

** Highlight Parenthesis
#+begin_src emacs-lisp
(use-package paren
  :config
  (set-face-attribute 'show-paren-match-expression nil :background "#363e4a")
  (show-paren-mode 1))
#+end_src

* UI Improvements
** Multiple Cursors
Initialize multiple cursors mode

#+begin_src emacs-lisp
(use-package multiple-cursors
  :ensure t)
#+end_src

** Which-key

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1))
#+end_src

* Dired
Found this dired configuration changes over on the [[explog.in/dot/emacs/config.html][A literate emacs configuration]]. It removes permissions and other details from the dired view which makes the buffer look a lot less noisy.

#+begin_src emacs-lisp
(add-hook 'dired-mode-hook
	  (lambda ()
	    (dired-hide-details-mode 1)
	    (display-line-numbers-mode 0)))
#+end_src

* Spell Checking
Use fly-spell to spell check certain types of buffers
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'turn-on-flyspell)
#+end_src

* Org Mode
** General
General setup for org mode files, some of this is to enhance
readability as well as associate certain minor modes and other
constants.

Additionally I prefer my org files to starup collapse for easier navigation.

#+begin_src emacs-lisp
   
(defun efs/org-mode-setup ()
  (org-indent-mode)
  (variable-pitch-mode 1)
  (visual-line-mode 1))

(use-package org
;;  :pin org
  :hook (org-mode . efs/org-mode-setup)
  :ensure org-contrib
  :bind (("C-c a" . org-agenda))
  :config
  (auto-fill-mode)
  (setq org-startup-folded "fold")
  (setq org-ellipsis " ▾")
  (setq org-return-follows-link t)
  (setq org-agenda-start-with-log-mode t)
  (setq org-log-done 'time)
  (setq org-log-into-drawer t))
#+end_src

** Babel
Setup babel source code blocks. Right now this is configured for shell and emacs-lisp.

The final line prevents org src code from altering the windowing within emacs. I borrows and existing window rather than doing a 50/50 split between the org target buffer and the source, which is super annoying.

#+begin_src emacs-lisp
(setf org-src-preserve-indentation t)

(org-babel-do-load-languages 'org-babel-load-languages
			     '((shell .t)
			       (emacs-lisp . t)))

(setf org-src-window-setup 'other-window)
#+end_src

** Structure Templates

 #+begin_src emacs-lisp

 (require 'org-tempo)
  
 (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
 (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
 (add-to-list 'org-structure-template-alist '("py" . "src python"))

 #+end_src
 
** Auto-tangle

This snippet adds a hook to org-mode buffers so that efs/org-babel-tangle-config gets executed each time such a buffer gets saved. This function checks to see if the file being saved is the Emacs.org file you’re looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp
;; Automatically tangle our Emacs.org config file when we save it
(defun efs/org-babel-tangle-config ()
  (when (string-equal (file-name-directory (buffer-file-name))
                      (expand-file-name user-emacs-directory))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
#+end_src

** Center Org Buffers

We use visual-fill-column to center org-mode buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document. This is really a matter of personal preference so you can remove the block below if you don’t like the behavior.

#+begin_src emacs-lisp
(defun efs/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . efs/org-mode-visual-fill))
#+end_src

** Better Bullets
org-bullets replaces the heading stars in org-mode buffers with nicer looking characters that you can control. Another option for this is org-superstar-mode which we may cover in a later video.

#+begin_src emacs-lisp
(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src

** Org Agenda

Setup some default bindings as well as the location of agenda files. The final line is a configuration change similar to the one made for org-babel. By default opening an agenda buffer reorganizes the windows and frames so that only the current buffer and the new agenda buffer are presented in a 50/50 window split. This is super annoying.

#+begin_src emacs-lisp
(setf org-agenda-files '("~/notes/journal"))
(global-set-key (kbd "C-c a") 'org-agenda)

(setf org-agenda-window-setup 'other-window)
#+end_src

** Resume
Setup some conviencing functions and bindings for resume org files.
#+begin_src emacs-lisp
(defun org-export-as-pdf-and-open ()
  (interactive)
  (save-buffer)
  (org-open-file (org-latex-export-to-pdf)))

(add-hook 
 'org-mode-hook
 (lambda()
   (define-key org-mode-map 
       (kbd "<f5>") 'org-export-as-pdf-and-open)))
#+end_src

** LaTeX Pdf Process
Need to add the -shell-escape option to the pdflatex process in order for svg files to be processed by inkscape

#+begin_src emacs-lisp
(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
	"bibtex %b"
	"pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
	"pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src

** org-roam
Setup org-roam note taking and file management. After loading the package, you can check the variable `org-roam--sqlite-available-p' to verify that the sqlite database is available.

#+begin_src emacs-lisp
(use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/notes")
  (org-agenda-files '("~/notes/journal"
		      "~/notes/globals/"))
  (org-roam-dailies-directory "journal/")
  (org-roam-completion-everywhere t)
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new (file+head "%<%Y%m%d%H%M%S$>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)
     ("h" "house project" plain
      (file "~/org/templates/house-project.org")
      :if-new (file+head "%<%Y%m%d%H%M%S$>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)))
  :bind  (("C-c n l" . org-roam-buffer-toggle)
	  ("C-c n f" . org-roam-node-find)
	  ("C-c n i" . org-roam-node-insert)	  
	  :map org-mode-map
	  ("C-M-i"   . completion-at-point)
	  :map org-roam-dailies-map
	  ("Y" . org-roam-dailies-capture-yesterday)
	  ("T" . org-roam-dailies-capture-tomorrow))
  :bind-keymap
  ("C-c n d" . org-roam-dailies-map)
  :config
  (require 'org-roam-dailies)
  (org-roam-db-autosync-mode))
#+end_src

** org-contacts
Use org-contacts to create and manage contacts in org mode.

#+begin_src emacs-lisp
(use-package org-contacts
  :ensure nil
  :after org
  :custom (org-contacts-files '("~/org/contacts.org")))
#+end_src

** org-capture
Customizations to org mode capture templates
#+begin_src 
(use-package org-capture
  :ensure nil
  :after org
  :custom
  (org-capture-templates
   `(("f" "Friend" entry (file+headline "~/org/contacts.org" "Friends"),
      (file "~/org/templates/contact-friend.org")
      :empty-lines 1))))
#+end_src

* Ivy and Counsel
#+begin_src emacs-lisp
(use-package ivy
  :diminish
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))

(use-package counsel
  :bind (("C-M-j" . 'counsel-switch-buffer)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))
  :custom
  (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
  :config
  (counsel-mode 1))

(use-package ivy-rich
  :init
  (ivy-rich-mode 1))

#+end_src

* Magit
#+begin_src emacs-lisp
(use-package magit
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

;; NOTE: Make sure to configure a GitHub token before using this package!
;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
(use-package forge)

#+end_src

* Programming
** Flycheck
Flycheck mode for syntax highlighting and linting
#+begin_src emacs-lisp

(use-package flycheck)

#+end_src

** Language Server Protocol
Basic LSP setup

#+begin_src emacs-lisp

(defun efs/lsp-mode-setup ()
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
  (lsp-headerline-breadcrumb-mode))

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook (lsp-mode . efs/lsp-mode-setup)
  :init
  (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
  :config
  (lsp-enable-which-key-integration t))

#+end_src

LSP-UI
#+begin_src emacs-lisp
(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :custom
  (lsp-ui-doc-position 'bottom))
#+end_src

LSP-treemacs
#+begin_src emacs-lisp
(use-package lsp-treemacs
  :after lsp)
#+end_src

** DAP
#+begin_src 
(use-package dap-mode
  ;; Uncomment the config below if you want all UI panes to be hidden by default!
  ;; :custom
  ;; (lsp-enable-dap-auto-configure nil)
  ;; :config
  ;; (dap-ui-mode 1)

  :config
  ;; Set up Node debugging
  (require 'dap-node)
  (dap-node-setup) ;; Automatically installs Node debug adapter if needed

  ;; Bind `C-c l d` to `dap-hydra` for easy access
  (general-define-key
    :keymaps 'lsp-mode-map
    :prefix lsp-keymap-prefix
    "d" '(dap-hydra t :wk "debugger")))
#+end_src

** Company 

Company Mode provides a nicer in-buffer completion interface than completion-at-point which is more reminiscent of what you would expect from an IDE. We add a simple configuration to make the keybindings a little more useful (TAB now completes the selection and initiates completion at the current location if needed).

We also use company-box to further enhance the look of the completions with icons and better overall presentation.

#+begin_src emacs-lisp

(use-package company
  :after lsp-mode
  :hook (lsp-mode . company-mode)
  :bind (:map company-active-map
         ("<tab>" . company-complete-selection))
        (:map lsp-mode-map
         ("<tab>" . company-indent-or-complete-common))
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.0))

(use-package company-box
  :hook (company-mode . company-box-mode))

#+end_src

** Projectile

#+begin_src emacs-lisp
(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  :custom ((projectile-completion-system 'ivy))
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  ;; NOTE: Set this to the folder where you keep your Git repos!
  (when (file-directory-p "~/projects/")
    (setq projectile-project-search-path '("~/projects/")))
  (setq projectile-switch-project-action #'projectile-dired))

(use-package counsel-projectile
  :config (counsel-projectile-mode))
#+end_src

** Languages
*** Emacs Lisp

Paredit mode

#+begin_src emacs-lisp
(use-package paredit
  :config
  
  ;; slurping in a terminal doesn't quite work, so rebind keys so they do
  (unless (display-graphic-p)
    (define-key paredit-mode-map (kbd ",") 'paredit-backward-slurp-sexp)
    (define-key paredit-mode-map (kbd ".") 'paredit-forward-slurp-sexp))

  ;; turn paredit on for all lispy modes
  (add-hook 'emacs-lisp-mode-hook 'paredit-mode)
  (add-hook 'lisp-mode-hook 'paredit-mode)
  (add-hook 'scheme-mode-hook 'paredit-mode)
  (add-hook 'ielm-mode-hook 'paredit-mode)

  ;; turn on paredit for Cask files too
  (add-to-list 'auto-mode-alist '("Cask" . paredit-mode)))
#+end_src

*** TypeScript
Setup Typescript to use lsp

#+begin_src emacs-lisp
(use-package typescript-mode
  :mode "\\.ts\\'"
  :hook (typescript-mode . lsp-deferred)
  :config
  (setq typescript-indent-level 2)
  (add-to-list 'lsp-enabled-clients 'ts-ls))
#+end_src

*** JSON
Setup json lsp
#+begin_src emacs-lisp
(use-package json-mode
  :hook (json-mode . lsp-deferred)
  :config
  (add-to-list 'lsp-enabled-clients 'json-ls))
#+end_src
*** Python

Setup lsp for python
#+begin_src emacs-lisp
(use-package python-mode
  :ensure t
  :hook (python-mode . lsp-deferred)
 ;; :custom
  ;; NOTE: Set these if Python 3 is called "python3" on your system!
  ;; (python-shell-interpreter "python3")
  ;; (dap-python-executable "python3")
;;  (dap-python-debugger 'debugpy)
;;  :config
;;  (require 'dap-python)
  )
#+end_src

**** pyenv
#+begin_src emacs-lisp
(use-package pyvenv
  :demand t
  :config
  (setq pyvenv-workon "emacs")  ; Default venv
  (pyvenv-tracking-mode 1))  ; Automatically use pyvenv-workon via dir-locals
#+end_src
**** Jedi Language Server

#+begin_src emacs-lisp
(use-package jedi)

(use-package lsp-jedi
  :ensure t
  :config
  (with-eval-after-load "lsp-mode"
    (add-to-list 'lsp-disabled-clients 'pyls)
    (add-to-list 'lsp-enabled-clients 'jedi)))
#+end_src

*** Open Scad
Initialize open scad mode
#+begin_src emacs-lisp
(use-package scad-mode)
(use-package scad-preview
  :mode "\\.scad\\'"
  :custom
  (scad-preview-image-size '(900 . 900))
  :config
  (defun scad-export-stl ()
    "Exports the current visited filename as an stl file."
    (interactive)
    (call-process "openscad" nil "*openscad-output*" t
                  "-o" (f-swap-ext (f-filename (buffer-file-name)) "stl")
                  (buffer-file-name))))
#+end_src

*** Lisp
**** Slime
#+begin_src
(use-package slime
  :custom
  (inferior-lisp-program "/usr/bin/sbcl")
  :config
  (add-hook 'lisp-mode-hook '(lambda () (slime-mode)))
  (slime-setup '(slime-repl slime-fuzzy)))
#+end_src

*** Lua 

Setup Lua the way I like it
#+begin_src emacs-lisp

(use-package lua-mode
  :hook (lua-mode . lsp-deferred)
  :config
  (add-to-list 'lsp-enabled-clients 'lsp-lua-lsp)
  (setf lsp-clients-lua-lsp-server-install-dir "~/.luarocks/bin/lua-lsp"))

#+end_src

**** Lua Language Server
Installation

#+begin_src sh
# clone project
git clone https://github.com/sumneko/lua-language-server
cd lua-language-server
git submodule update --init --recursive

cd 3rd/luamake
ninja -f ninja/linux.ninja
cd ../..
./3rd/luamake/luamake rebuild

mkdir -P ~/.emacs.d/.cache/lsp/lua-language-server/

cp bin/Linux/lua-language-server ~/.emacs.d/.cache/lsp/lua-language-server/
cp main.lua ~/.emacs.d/.cache/lsp/lua-language-server/
#+end_src

*** HTML
Add emmet mode to html mode
#+begin_src emacs-lisp
(use-package emmet-mode
  :hook (mhtml-mode . emmet-mode))
#+end_src

*** YAML
Setup yaml support
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src

** Origami
Origami folding library
#+begin_src emacs-lisp
(use-package origami
  :config
  (global-origami-mode))
#+end_src

** YAML
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src

* Docker 
** Docker File Mode
#+begin_src emacs-lisp
(use-package dockerfile-mode)
#+end_src

** Docker Compose 
#+begin_src emacs-lisp
(use-package docker-compose-mode
  :bind ("C-c D" . docker-compose))
#+end_src

** Docker Management
#+begin_src emacs-lisp
(use-package docker
  :ensure t
  :bind ("C-c d" . docker))
#+end_src

* Smartparens
Turn on smart parens mode for all programming modes. Exclude single quote parings for lisp modes because single quotes have different meaning in those languages.

#+begin_src emacs-lisp
(use-package smartparens
  :config
  (add-hook 'prog-mode-hook 'turn-on-smartparens-mode)
  (sp-local-pair '(emacs-lisp-mode lisp-mode) "'" "'" :actions nil))
#+end_src
* Treemacs
Default setup for treemacs
Disabling for the moment
#+begin_src
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay      0.5
          treemacs-directory-name-transformer    #'identity
          treemacs-display-in-side-window        t
          treemacs-eldoc-display                 t
          treemacs-file-event-delay              5000
          treemacs-file-extension-regex          treemacs-last-period-regex-value
          treemacs-file-follow-delay             0.2
          treemacs-file-name-transformer         #'identity
          treemacs-follow-after-init             t
          treemacs-git-command-pipe              ""
          treemacs-goto-tag-strategy             'refetch-index
          treemacs-indentation                   2
          treemacs-indentation-string            " "
          treemacs-is-never-other-window         nil
          treemacs-max-git-entries               5000
          treemacs-missing-project-action        'ask
          treemacs-move-forward-on-expand        nil
          treemacs-no-png-images                 nil
          treemacs-no-delete-other-windows       t
          treemacs-project-follow-cleanup        nil
          treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
          treemacs-position                      'left
          treemacs-recenter-distance             0.1
          treemacs-recenter-after-file-follow    nil
          treemacs-recenter-after-tag-follow     nil
          treemacs-recenter-after-project-jump   'always
          treemacs-recenter-after-project-expand 'on-distance
          treemacs-show-cursor                   nil
          treemacs-show-hidden-files             t
          treemacs-silent-filewatch              nil
          treemacs-silent-refresh                nil
          treemacs-sorting                       'alphabetic-asc
          treemacs-space-between-root-nodes      t
          treemacs-tag-follow-cleanup            t
          treemacs-tag-follow-delay              1.5
          treemacs-user-mode-line-format         nil
          treemacs-user-header-line-format       nil
          treemacs-width                         20
          treemacs-workspace-switch-cleanup      nil)))
#+end_src

* yassnippet
#+begin_src emacs-lisp
(use-package yasnippet
  :custom
  (yas/root-directory '("~/.emacs.d/snippets"))
  :config
  (yas-global-mode 1)
  (mapc #'yas-load-directory yas/root-directory))

#+end_src

* RestClient
#+begin_src emacs-lisp
(use-package restclient)
#+end_src

* Customization
Customization's to emacs. Emacs adds these based on some user interaction so they need to be added into the org file so they persist after another tangle.

#+begin_src emacs-lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(safe-local-variable-values
   '((gac-automatically-push-p . t)
     (gac-automatically-add-new-files-p . t))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
#+end_src

* Closing

#+begin_src emacs-lisp
;;; init.el ends here
#+end_src
